title: CodingCareBear
email: carey.harrell@outlook.com
description: >-
  Power BI, Tableau, and Streamlit dashboards featuring machine learning and health analytics.
baseurl: ""
url: "https://codingcarebear.github.io"
theme: minima